## USB port
port: /dev/ttyTHS1


##### Calibration ####
### accelerometer
accel_x_min: -283.0
accel_x_max: 282.0
accel_y_min: -278.0
accel_y_max: 289.0
accel_z_min: -293.0
accel_z_max: 210.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [84.3426, -38.5076, -12.8131]
magn_ellipsoid_transform: [[0.899142, 0.0139406, -0.00801530], [0.0139406, 0.927459, 0.0132483], [0.00801530, 0.0132483, 0.996444]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -102.03
gyro_average_offset_y: -35.62
gyro_average_offset_z: 13.27
