## USB port
port: /dev/ttyTHS1


##### Calibration ####
### accelerometer
accel_x_min: -283.0
accel_x_max: 284.0
accel_y_min: -284.0
accel_y_max: 290.0
accel_z_min: -283.0
accel_z_max: 219.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [175.132, 2.90911, -45.4627]
magn_ellipsoid_transform: [[0.707745, 0.0469397, -0.0416831], [0.0469397, 0.0765720, 0.0203769], [-0.0416831, 0.0203769, 0.993229]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -3.17
gyro_average_offset_y: -39.52
gyro_average_offset_z: 16.82
